DEFAULT:
  PORT: 5000

S3:
  BUCKET_NAME: your_bucket_name
  REGION_NAME: your_region_name
  ENDPOINT_URL: http://localhost:9000  # MinIO endpoint URL, comment out if using AWS S3

USE_MINIO: true  # Set to true to use MinIO, false to use AWS S3